DROP TABLE TBL_BIDS;

CREATE TABLE TBL_BIDS (
	ID_BID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    USERNAME_BID VARCHAR(20),
	TITLE_BID VARCHAR(50),
	AMOUNT_BID int
);
