INSERT INTO TBL_ITEMS(USERNAME, TITLE, CATEGORY, PICTURE, DESCRIPTON, POSTAGEDETAILS, RESERVEPRICE, BIDDINGSTARTPRICE, BIDDINGINCREMENTS, TIMEFORBIDDING, ADDEDTIMEFORBIDDING) VALUES ('yunus', 'Playstation', 'game', 'playstation-picture', 'it is a good playstation.', 'UNSW Physics Department',50,10,1, 5,6);



