DROP TABLE TBL_ITEMS;

CREATE TABLE TBL_ITEMS (
	ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    USERNAME VARCHAR(20),
	TITLE VARCHAR(50) ,
	CATEGORY VARCHAR(20),
	PICTURE VARCHAR(20),
	DESCRIPTON VARCHAR(200),
	POSTAGEDETAILS VARCHAR(50),
	RESERVEPRICE INT,
	BIDDINGSTARTPRICE INT,
	BIDDINGINCREMENTS INT,
	TIMEFORBIDDING INT,
	ADDEDTIMEFORBIDDING INT
);
