UPDATE TBL_USERS
SET USERNAME='huseyin', PASSWORD='huse', EMAIL_ADD='huseyin@gmail.com', NICKNAME='huse', FIRSTNAME='huseyin',LASTNAME='bilge', YEAROFBIRTH='1967-03-12', FULLADDRESS='19 McCabe Street',CREDITCARDNUMBER='121231-12-12'
WHERE USERNAME='huseyin';
