
CREATE TABLE TBL_USERS_TEMP (
	USERNAME VARCHAR(20) PRIMARY KEY,
	VAL VARCHAR(20),
	PASSWORD VARCHAR(20),
	EMAIL_ADD VARCHAR(40),
	NICKNAME VARCHAR(40),
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(30),
	YEAROFBIRTH DATE,
	FULLADDRESS VARCHAR(200),
	CREDITCARDNUMBER VARCHAR(50)
);
